package unitestLibs;

public class Constants {
	
	public static final String[] VALID_QUANTITIES = {
        "zero", "one", "two", "few", "many", "other"
    };
	
	public static final String[] STRING_VALUES = {
		"Java", "PHP", "C and C++", "Javascript", "SQLite", "HTML5"
    };
	
	public static final String RES_ROOT = "./unitest/res";
	
	public static final String RES_XML_NAME = "strings.xml";
	
	public static final String[] RES_PATHS = {
		Constants.RES_ROOT + "/values/" + Constants.RES_XML_NAME,
		Constants.RES_ROOT + "/values-en/" + Constants.RES_XML_NAME,
		Constants.RES_ROOT + "/values-zh/" + Constants.RES_XML_NAME,
		Constants.RES_ROOT + "/values-jp/" + Constants.RES_XML_NAME
	};
	
	public static final String TEST_RES_ROOT = "./unitest/unitestRes";
	
	public static final String TEST_RES_JSON = Constants.TEST_RES_ROOT + "/strings.json";
	
	public static final String TEST_RES_JSON_CONTENT =   ""
														+"{"
														+"    \"name\" : \"Name\","
														+"    \"age\" : 18,"
														+"    \"addr\" : \"abc, def, 987 fg, jkl\","
														+"    \"array\" : [0, 1, 2, 3]"
														+"}";
	
	public static class JSONSource {

		public static class StringSource {
			
			public static final String NORMAL_CASE = ""
				+"[" // 4 valid string resources
				+	"{"
				+		"\"name\" : \"s0\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s0\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s0_in_Espanol\""
				+			"}"
				+		"]"
				+	"}, "
				+	"{"
				+		"\"name\" : \"s1\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s1\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s1_in_Espanol\""
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_NAME_CASE = ""
				+"[" // 0 valid string resources
				+	"{"
				+		"\"name\" : \"\"," // Invalid name
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s0\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s0_in_Espanol\""
				+			"}"
				+		"]"
				+	"}, "
				+	"{"
				+		"\"name\" : null," // Invalid name
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s1\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s1_in_Espanol\""
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_LANG_CASE = ""
				+"[" // 2 valid string resources
				+	"{"
				+		"\"name\" : \"s0\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"\"," // Invalid lang
				+				"\"strValue\" : \"s0\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s0_in_Espanol\""
				+			"}"
				+		"]"
				+	"}, "
				+	"{"
				+		"\"name\" : \"s1\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s1\""
				+			"}, "
				+			"{"
				+				"\"lang\" : null," // Invalid lang
				+				"\"strValue\" : \"s1_in_Espanol\""
				+			"}"
				+		"]"
				+	"}"
				+"]";		
			
			public static final String INVALID_FORMAT_CASE = ""
				+"[" // 0 valid string resources
				+	"{"
				+		"\"naem\" : \"s0\"," // Invalid
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s0\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s0_in_Espanol\""
				+			"}"
				+		"]"
				+	"}, "
				+	"{"
				+		"\"name\" : \"s1\","
				+		"\"res\" : [" // Invalid
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"strValue\" : \"s1\""
				+			"}, "
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"strValue\" : \"s1_in_Espanol\""
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
		}
		
		public static class StringArraySource {
			
			public static final String NORMAL_CASE = ""
				+"[" // 4 valid resources
				+	"{"
				+		"\"name\" : \"country_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : [ \"Canada\", \"Norway\" ]"
				+			"},"
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Canada_in_Espanol\", \"Norway_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"flower_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : [ \"Rose\", \"Tulip\" ]"
				+			"},"				
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Rose_in_Espanol\", \"Tulip_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_NAME_CASE = ""
				+"[" // 0 valid resources
				+	"{"
				+		"\"name\" : \"\"," // Invalid
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : [ \"Canada\", \"Norway\" ]"
				+			"},"
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Canada_in_Espanol\", \"Norway_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : null," // Invalid
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : [ \"Rose\", \"Tulip\" ]"
				+			"},"				
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Rose_in_Espanol\", \"Tulip_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_LANG_CASE = ""
				+"[" // 2 valid resources
				+	"{"
				+		"\"name\" : \"country_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"\"," // Invalid
				+				"\"items\" : [ \"Canada\", \"Norway\" ]"
				+			"},"
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Canada_in_Espanol\", \"Norway_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"flower_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : null," // Invalid
				+				"\"items\" : [ \"Rose\", \"Tulip\" ]"
				+			"},"				
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Rose_in_Espanol\", \"Tulip_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_ITEMS_CASE = ""
				+"[" // 1 valid resources
				+	"{"
				+		"\"name\" : \"country_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : [ null, \"Norway\" ]" // Valid!
				+			"},"
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : {}" // Invalid
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"flower_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : []" // Invalid
				+			"},"				
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : \"items\"" // Invalid
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_FORMAT_CASE = ""
				+"[" // 1 valid resources
				+	"[]," // Invalid
				+	"{"
				+		"\"name\" : \"flower_list\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"language\" : \"en\"," // Invalid
				+				"\"items\" : [ \"Rose\", \"Tulip\" ]"
				+			"},"				
				+			"{"
				+				"\"lang\" : \"es\","
				+				"\"items\" : [ \"Rose_in_Espanol\", \"Tulip_in_Espanol\" ]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
		}
	
		public static class QuantityStringSource {
			
			public static final String NORMAL_CASE = ""
				+"[" // 8 valid resources
				+	"{"
				+		"\"name\" : \"number_of_songs\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"number_of_cats\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_NAME_CASE = ""
				+"[" // 4 valid resources
				+	"{"
				+		"\"name\" : \"\"," // Invalid
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : []," // Valid
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_LANG_CASE = ""
				+"[" // 4 valid resources
				+	"{"
				+		"\"name\" : \"number_of_songs\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"\"," // Invalid
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : null," // Invalid
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"number_of_cats\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_QUANTITY_CASE = ""
				+"[" // 6 valid resources
				+	"{"
				+		"\"name\" : \"number_of_songs\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"\"," // Invalid
				+						"\"strValue\" : \"One song\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : null," // Invalid
				+						"\"strValue\" : \"%d song_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"number_of_cats\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"{"			
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"quantity\" : \"two\","
				+						"\"strValue\" : \"2 cats_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
			public static final String INVALID_FORMAT_CASE = ""
				+"[" // 1 valid resources
				+	"{"
				+		"\"name\" : \"number_of_songs\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"itemNodes\" : [" // Invalid
				+					"{"			
				+						"\"quantity\" : \"one\","
				+						"\"strValue\" : \"One song\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d song\""
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : {}" // Invalid 
				+			"}"
				+		"]"
				+	"},"
				+	"{"
				+		"\"name\" : \"number_of_cats\","
				+		"\"resources\" : ["
				+			"{"
				+				"\"lang\" : \"en\","
				+				"\"items\" : ["
				+					"0," // Invalid
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"stringValue\" : \"%d cats\"" // Invalid
				+					"}"
				+				"]"
				+			"},"			
				+			"{"	
				+				"\"lang\" : \"es\","
				+				"\"items\" : ["
				+					"{"
				+						"\"Quantity\" : \"two\"," // Invalid
				+						"\"strValue\" : \"2 cats_in_Espanol\""
				+					"},"
				+					"{"
				+						"\"quantity\" : \"other\","
				+						"\"strValue\" : \"%d cats_in_Espanol\""
				+					"}"
				+				"]"
				+			"}"
				+		"]"
				+	"}"
				+"]";
			
		}
	}
}